name: Cypress Suite

on:
  pull_request:
    branches: master

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: "node_modules"
          key: ${{ runner.os }}-yarn-${{hashFiles('yarn.lock')}}

      - name: Cache Cypress
        uses: actions/cache@v3
        id: cache-cypress
        with:
          path: "/github/home/.cache/"
          key: ${{ runner.os }}-cypress-${{hashFiles('/github/home/.cache/')}}

  ui-chrome-tests:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-yarn-${{hashFiles('yarn.lock')}}
      - name: Cache Cypress
        uses: actions/cache@v3
        id: cache-cypress
        with:
          path: "/github/home/.cache/"
          key: ${{ runner.os }}-cypress-${{hashFiles('/github/home/.cache/')}}
      - run: pwd
      - run: ls -a
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
